# Generated by Django 4.2 on 2023-05-19 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('technicalquestions_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeElapsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date_start', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_elapsed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
