# Generated by Django 4.2 on 2023-05-09 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapeJob',
            fields=[
                ('job_name', models.CharField(max_length=500, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_resp', models.JSONField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('job_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='jobscrape_api.scrapejob')),
            ],
        ),
    ]
